// GENERATED by scripts/import-vscode-themes.mjs from microsoft/vscode 1.127.0.
// Do not edit by hand — re-run the script to refresh.
import type { IThemeFile } from "../IThemeFile.ts";

export const dark2026Theme: IThemeFile = {
    name: "Dark 2026",
    type: "dark",
    colors: {
        "checkbox.border": "#707070",
        "editor.background": "#121314",
        "editor.foreground": "#BBBEBF",
        "editor.inactiveSelectionBackground": "#27678260",
        "editorIndentGuide.background1": "#404040",
        "editorIndentGuide.activeBackground1": "#707070",
        "editor.selectionHighlightBackground": "#27678260",
        "list.dropBackground": "#3994BC1A",
        "activityBarBadge.background": "#3994BC",
        "sideBarTitle.foreground": "#bfbfbf",
        "input.placeholderForeground": "#555555",
        "menu.background": "#202122",
        "menu.foreground": "#bfbfbf",
        "menu.separatorBackground": "#2A2B2C",
        "menu.border": "#2A2B2CFF",
        "menu.selectionBackground": "#3994BC26",
        "statusBarItem.remoteForeground": "#FFFFFF",
        "statusBarItem.remoteBackground": "#0078D4",
        "ports.iconRunningProcessForeground": "#369432",
        "sideBarSectionHeader.background": "#191A1B",
        "sideBarSectionHeader.border": "#2A2B2CFF",
        "tab.selectedBackground": "#222222",
        "tab.selectedForeground": "#ffffffa0",
        "tab.lastPinnedBorder": "#2A2B2CFF",
        "list.activeSelectionIconForeground": "#FFF",
        "terminal.inactiveSelectionBackground": "#3A3D41",
        "widget.border": "#2A2B2CFF",
        "actionBar.toggledBackground": "#383a49",
        "agentsPanel.border": "#2A2B2CFF",
        "agentsChatInput.border": "#333536",
        "agentsChatInput.focusBorder": "#3994BCB3",
        "agentsNewSessionButton.border": "#333536",
        "activityBar.activeBorder": "#bfbfbf",
        "activityBar.background": "#191A1B",
        "activityBar.border": "#2A2B2CFF",
        "activityBar.foreground": "#bfbfbf",
        "activityBar.inactiveForeground": "#8C8C8C",
        "activityBarBadge.foreground": "#FFFFFF",
        "badge.background": "#3994BCF0",
        "badge.foreground": "#FFFFFF",
        "button.background": "#297AA0",
        "button.border": "#297AA0",
        "button.foreground": "#FFFFFF",
        "button.hoverBackground": "#2B7DA3",
        "button.secondaryBackground": "#00000000",
        "button.secondaryForeground": "#CCCCCC",
        "button.secondaryHoverBackground": "#FFFFFF10",
        "chat.slashCommandBackground": "#26477866",
        "chat.slashCommandForeground": "#85B6FF",
        "chat.editedFileForeground": "#E2C08D",
        "checkbox.background": "#242526",
        "debugToolBar.background": "#181818",
        descriptionForeground: "#8C8C8C",
        "dropdown.background": "#191A1B",
        "dropdown.border": "#333536",
        "dropdown.foreground": "#bfbfbf",
        "dropdown.listBackground": "#191A1B",
        "editor.findMatchBackground": "#27678290",
        "editorGroup.border": "#FFFFFF17",
        "editorGroupHeader.tabsBackground": "#191A1B",
        "editorGroupHeader.tabsBorder": "#2A2B2CFF",
        "editorGutter.addedBackground": "#72C892",
        "editorGutter.deletedBackground": "#F28772",
        "editorGutter.modifiedBackground": "#0078D4",
        "editorLineNumber.activeForeground": "#BBBEBF",
        "editorLineNumber.foreground": "#858889",
        "editorOverviewRuler.border": "#2A2B2CFF",
        "editorWidget.background": "#202122",
        errorForeground: "#f48771",
        focusBorder: "#3994BCB3",
        foreground: "#bfbfbf",
        "icon.foreground": "#8C8C8C",
        "input.background": "#191A1B",
        "input.border": "#333536FF",
        "input.foreground": "#bfbfbf",
        "inputOption.activeBackground": "#3994BC33",
        "inputOption.activeBorder": "#2A2B2CFF",
        "keybindingLabel.foreground": "#CCCCCC",
        "notificationCenterHeader.background": "#242526",
        "notificationCenterHeader.foreground": "#bfbfbf",
        "notifications.background": "#202122",
        "notifications.border": "#2A2B2CFF",
        "notifications.foreground": "#bfbfbf",
        "panel.background": "#191A1B",
        "panel.border": "#2A2B2CFF",
        "panelInput.border": "#2B2B2B",
        "panelTitle.activeBorder": "#3994BC",
        "panelTitle.activeForeground": "#bfbfbf",
        "panelTitle.inactiveForeground": "#8C8C8C",
        "peekViewEditor.background": "#191A1B",
        "peekViewEditor.matchHighlightBackground": "#3994BC33",
        "peekViewResult.background": "#191A1B",
        "peekViewResult.matchHighlightBackground": "#3994BC33",
        "pickerGroup.border": "#2A2B2CFF",
        "progressBar.background": "#878889",
        "quickInput.background": "#202122",
        "quickInput.foreground": "#bfbfbf",
        "settings.dropdownBackground": "#313131",
        "settings.dropdownBorder": "#3C3C3C",
        "settings.headerForeground": "#FFFFFF",
        "settings.modifiedItemIndicator": "#BB800966",
        "sideBar.background": "#191A1B",
        "sideBar.border": "#2A2B2CFF",
        "sideBar.foreground": "#bfbfbf",
        "sideBarSectionHeader.foreground": "#bfbfbf",
        "statusBar.background": "#191A1B",
        "statusBar.border": "#2A2B2CFF",
        "statusBarItem.hoverBackground": "#323233",
        "statusBarItem.hoverForeground": "#FFFFFF",
        "statusBar.debuggingBackground": "#3994BC",
        "statusBar.debuggingForeground": "#FFFFFF",
        "statusBar.focusBorder": "#3994BCB3",
        "statusBar.foreground": "#8C8C8C",
        "statusBar.noFolderBackground": "#191A1B",
        "statusBarItem.focusBorder": "#3994BCB3",
        "statusBarItem.prominentBackground": "#3994BC",
        "tab.activeBackground": "#121314",
        "tab.activeBorder": "#121314",
        "tab.activeBorderTop": "#3994BC",
        "tab.activeForeground": "#bfbfbf",
        "tab.selectedBorderTop": "#6caddf",
        "tab.border": "#2A2B2CFF",
        "tab.hoverBackground": "#121314",
        "tab.inactiveBackground": "#191A1B",
        "tab.inactiveForeground": "#8C8C8C",
        "tab.unfocusedActiveBorder": "#1F1F1F",
        "tab.unfocusedActiveBorderTop": "#2B2B2B",
        "tab.unfocusedHoverBackground": "#1F1F1F",
        "terminal.foreground": "#CCCCCC",
        "terminal.tab.activeBorder": "#3994BC00",
        "textBlockQuote.background": "#242526",
        "textBlockQuote.border": "#2A2B2CFF",
        "textCodeBlock.background": "#242526",
        "textLink.activeForeground": "#53A5CA",
        "textLink.foreground": "#48A0C7",
        "textPreformat.foreground": "#8C8C8C",
        "textPreformat.background": "#262626",
        "textSeparator.foreground": "#2a2a2aFF",
        "titleBar.activeBackground": "#191A1B",
        "titleBar.activeForeground": "#8C8C8C",
        "titleBar.border": "#2A2B2CFF",
        "titleBar.inactiveBackground": "#191A1B",
        "titleBar.inactiveForeground": "#8C8C8C",
        "welcomePage.tileBackground": "#2B2B2B",
        "welcomePage.progress.foreground": "#0078D4",
        disabledForeground: "#555555",
        "button.secondaryBorder": "#333536",
        "checkbox.foreground": "#8C8C8C",
        "inputOption.activeForeground": "#bfbfbf",
        "inputValidation.infoBackground": "#1E3A47",
        "inputValidation.infoBorder": "#3994BC",
        "inputValidation.infoForeground": "#bfbfbf",
        "inputValidation.warningBackground": "#352A05",
        "inputValidation.warningBorder": "#B89500",
        "inputValidation.warningForeground": "#bfbfbf",
        "inputValidation.errorBackground": "#3A1D1D",
        "inputValidation.errorBorder": "#BE1100",
        "inputValidation.errorForeground": "#bfbfbf",
        "scrollbar.shadow": "#191B1D4D",
        "scrollbarSlider.background": "#A8A9AA85",
        "scrollbarSlider.hoverBackground": "#A8A9AA90",
        "scrollbarSlider.activeBackground": "#A8A9AA9C",
        "list.activeSelectionBackground": "#3994BC26",
        "list.activeSelectionForeground": "#ededed",
        "list.inactiveSelectionBackground": "#2C2D2E",
        "list.inactiveSelectionForeground": "#ededed",
        "list.hoverBackground": "#1E1F20",
        "list.hoverForeground": "#bfbfbf",
        "toolbar.hoverBackground": "#323233",
        "toolbar.activeBackground": "#3C3C3D",
        "list.focusBackground": "#3994BC26",
        "list.focusForeground": "#bfbfbf",
        "list.focusOutline": "#3994BCB3",
        "list.highlightForeground": "#48A0C7",
        "list.invalidItemForeground": "#444444",
        "list.errorForeground": "#f48771",
        "list.warningForeground": "#e5ba7d",
        "activityBar.activeFocusBorder": "#3994BCB3",
        "activityBarTop.activeBorder": "#bfbfbf",
        "menubar.selectionBackground": "#242526",
        "menubar.selectionForeground": "#bfbfbf",
        "menu.selectionForeground": "#bfbfbf",
        "menu.selectionBorder": "#3994BC",
        "commandCenter.foreground": "#bfbfbf",
        "commandCenter.activeForeground": "#bfbfbf",
        "commandCenter.background": "#191A1B",
        "commandCenter.activeBackground": "#FFFFFF0F",
        "commandCenter.border": "#2E3031",
        "editorStickyScroll.background": "#121314",
        "editorStickyScrollHover.background": "#202122",
        "editorStickyScroll.border": "#2A2B2CFF",
        "editorCursor.foreground": "#BBBEBF",
        "editor.selectionBackground": "#276782dd",
        "editor.wordHighlightBackground": "#27678250",
        "editor.wordHighlightStrongBackground": "#27678280",
        "editor.findMatchHighlightBackground": "#27678280",
        "editor.findRangeHighlightBackground": "#242526",
        "editor.hoverHighlightBackground": "#242526",
        "editor.lineHighlightBackground": "#242526",
        "editor.rangeHighlightBackground": "#242526",
        "editorLink.activeForeground": "#3a94bc",
        "editorWhitespace.foreground": "#8C8C8C4D",
        "editorIndentGuide.background": "#8384854D",
        "editorIndentGuide.activeBackground": "#838485",
        "editorRuler.foreground": "#848484",
        "editorCodeLens.foreground": "#8C8C8C",
        "editorBracketMatch.background": "#3994BC55",
        "editorBracketMatch.border": "#2A2B2CFF",
        "editorWidget.border": "#2A2B2CFF",
        "editorWidget.foreground": "#bfbfbf",
        "editorSuggestWidget.background": "#202122",
        "editorSuggestWidget.border": "#2A2B2CFF",
        "editorSuggestWidget.foreground": "#bfbfbf",
        "editorSuggestWidget.highlightForeground": "#bfbfbf",
        "editorSuggestWidget.selectedBackground": "#3994BC26",
        "editorHoverWidget.background": "#202122",
        "editorHoverWidget.border": "#2A2B2CFF",
        "peekView.border": "#2A2B2CFF",
        "peekViewResult.fileForeground": "#bfbfbf",
        "peekViewResult.lineForeground": "#8C8C8C",
        "peekViewResult.selectionBackground": "#3994BC26",
        "peekViewResult.selectionForeground": "#bfbfbf",
        "peekViewTitle.background": "#242526",
        "peekViewTitleDescription.foreground": "#8C8C8C",
        "peekViewTitleLabel.foreground": "#bfbfbf",
        "editorGutter.background": "#121314",
        "diffEditor.insertedLineBackground": "#347d3926",
        "diffEditor.insertedTextBackground": "#57ab5a4d",
        "diffEditor.removedLineBackground": "#c93c3726",
        "diffEditor.removedTextBackground": "#f470674d",
        "editorOverviewRuler.findMatchForeground": "#3a94bc99",
        "editorOverviewRuler.modifiedForeground": "#6ab890",
        "editorOverviewRuler.addedForeground": "#73c991",
        "editorOverviewRuler.deletedForeground": "#f48771",
        "editorOverviewRuler.errorForeground": "#f48771",
        "editorOverviewRuler.warningForeground": "#e5ba7d",
        "statusBar.noFolderForeground": "#8C8C8C",
        "statusBarItem.activeBackground": "#4B4C4D",
        "statusBarItem.prominentForeground": "#FFFFFF",
        "statusBarItem.prominentHoverBackground": "#3994BC",
        "tab.hoverForeground": "#bfbfbf",
        "tab.unfocusedActiveBackground": "#121314",
        "tab.unfocusedActiveForeground": "#8C8C8C",
        "tab.unfocusedInactiveBackground": "#191A1B",
        "tab.unfocusedInactiveForeground": "#444444",
        "breadcrumb.foreground": "#8C8C8C",
        "breadcrumb.background": "#121314",
        "breadcrumb.focusForeground": "#bfbfbf",
        "breadcrumb.activeSelectionForeground": "#bfbfbf",
        "breadcrumbPicker.background": "#202122",
        "notificationCenter.border": "#2A2B2CFF",
        "notificationToast.border": "#2A2B2CFF",
        "notificationLink.foreground": "#3a94bc",
        "notificationsWarningIcon.foreground": "#CCA700",
        "notificationsErrorIcon.foreground": "#f48771",
        "notificationsInfoIcon.foreground": "#3a94bc",
        "activityWarningBadge.foreground": "#202020",
        "activityWarningBadge.background": "#CCA700",
        "activityErrorBadge.foreground": "#FFFFFF",
        "activityErrorBadge.background": "#f48771",
        "extensionButton.prominentBackground": "#297AA0",
        "extensionButton.prominentForeground": "#FFFFFF",
        "extensionButton.prominentHoverBackground": "#2B7DA3",
        "pickerGroup.foreground": "#bfbfbf",
        "quickInputList.focusBackground": "#297AA0",
        "quickInputList.focusForeground": "#FFFFFF",
        "quickInputList.focusIconForeground": "#FFFFFF",
        "quickInputList.focusHighlightForeground": "#FFFFFF",
        "quickInputList.hoverBackground": "#1E1F20",
        "terminal.selectionBackground": "#3994BC33",
        "terminal.background": "#191A1B",
        "terminal.border": "#2A2B2CFF",
        "terminalCursor.foreground": "#bfbfbf",
        "terminalCursor.background": "#191A1B",
        "gitDecoration.addedResourceForeground": "#73c991",
        "gitDecoration.modifiedResourceForeground": "#e5ba7d",
        "gitDecoration.deletedResourceForeground": "#f48771",
        "gitDecoration.untrackedResourceForeground": "#73c991",
        "gitDecoration.ignoredResourceForeground": "#8C8C8C",
        "gitDecoration.conflictingResourceForeground": "#f48771",
        "gitDecoration.stageModifiedResourceForeground": "#e5ba7d",
        "gitDecoration.stageDeletedResourceForeground": "#f48771",
        "quickInputTitle.background": "#202122",
        "commandCenter.activeBorder": "#333536",
        "quickInput.border": "#333536",
        "gauge.foreground": "#59a4f9",
        "gauge.background": "#58A4F94D",
        "gauge.border": "#2A2C2EFF",
        "gauge.warningForeground": "#e5ba7d",
        "gauge.warningBackground": "#E3B97E4D",
        "gauge.errorForeground": "#f48771",
        "gauge.errorBackground": "#F287724D",
        "chat.requestBubbleBackground": "#ffffff13",
        "chat.requestBubbleHoverBackground": "#ffffff22",
        "chat.inputWorkingBorderColor1": "#297AA0",
        "chat.inputWorkingBorderColor2": "#1C546F",
        "chat.inputWorkingBorderColor3": "#5BA8CC",
        "editorCommentsWidget.rangeBackground": "#488FAE26",
        "editorCommentsWidget.rangeActiveBackground": "#488FAE46",
        "charts.foreground": "#CCCCCC",
        "charts.lines": "#C8CACC80",
        "charts.blue": "#57A3F8",
        "charts.red": "#EF8773",
        "charts.yellow": "#E0B97F",
        "charts.orange": "#CD861A",
        "charts.green": "#86CF86",
        "charts.purple": "#AD80D7",
        "inlineChat.border": "#00000000",
        "minimapSlider.background": "#A8A9AA85",
        "minimapSlider.hoverBackground": "#A8A9AA90",
        "minimapSlider.activeBackground": "#A8A9AA9C",
        "agents.background": "#121314",
        "agentsPanel.background": "#191A1B",
        "agentsPanel.foreground": "#bfbfbf",
        "agentsGradient.tintColor": "#297AA0",
        "agentsChatInput.background": "#202122",
        "agentsChatInput.foreground": "#bfbfbf",
        "agentsChatInput.placeholderForeground": "#555555",
        "agentsNewSessionButton.background": "#00000000",
        "agentsNewSessionButton.foreground": "#bfbfbf",
        "agentsNewSessionButton.hoverBackground": "#FFFFFF18",
        "agentsBadge.background": "#3994BC",
        "agentsBadge.foreground": "#FFFFFF",
        "agentsUnreadBadge.background": "#3994BC",
        "agentsUnreadBadge.foreground": "#FFFFFF",
    },
    tokenColors: [
        {
            settings: {
                foreground: "#D4D4D4",
            },
            scope: [
                "meta.embedded",
                "source.groovy.embedded",
                "string meta.image.inline.markdown",
                "variable.legacy.builtin.python",
            ],
        },
        {
            settings: {
                fontStyle: "italic",
            },
            scope: "emphasis",
        },
        {
            settings: {
                fontStyle: "bold",
            },
            scope: "strong",
        },
        {
            settings: {
                foreground: "#000080",
            },
            scope: "header",
        },
        {
            settings: {
                foreground: "#6A9955",
            },
            scope: "comment",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "constant.language",
        },
        {
            settings: {
                foreground: "#b5cea8",
            },
            scope: [
                "constant.numeric",
                "variable.other.enummember",
                "keyword.operator.plus.exponent",
                "keyword.operator.minus.exponent",
            ],
        },
        {
            settings: {
                foreground: "#646695",
            },
            scope: "constant.regexp",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "entity.name.tag",
        },
        {
            settings: {
                foreground: "#d7ba7d",
            },
            scope: ["entity.name.tag.css", "entity.name.tag.less"],
        },
        {
            settings: {
                foreground: "#9cdcfe",
            },
            scope: "entity.other.attribute-name",
        },
        {
            settings: {
                foreground: "#d7ba7d",
            },
            scope: [
                "entity.other.attribute-name.class.css",
                "source.css entity.other.attribute-name.class",
                "entity.other.attribute-name.id.css",
                "entity.other.attribute-name.parent-selector.css",
                "entity.other.attribute-name.parent.less",
                "source.css entity.other.attribute-name.pseudo-class",
                "entity.other.attribute-name.pseudo-element.css",
                "source.css.less entity.other.attribute-name.id",
                "entity.other.attribute-name.scss",
            ],
        },
        {
            settings: {
                foreground: "#f44747",
            },
            scope: "invalid",
        },
        {
            settings: {
                fontStyle: "underline",
            },
            scope: "markup.underline",
        },
        {
            settings: {
                foreground: "#569cd6",
                fontStyle: "bold",
            },
            scope: "markup.bold",
        },
        {
            settings: {
                foreground: "#569cd6",
                fontStyle: "bold",
            },
            scope: "markup.heading",
        },
        {
            settings: {
                foreground: "#C586C0",
                fontStyle: "italic",
            },
            scope: "markup.italic",
        },
        {
            settings: {
                fontStyle: "strikethrough",
            },
            scope: "markup.strikethrough",
        },
        {
            settings: {
                foreground: "#b5cea8",
            },
            scope: "markup.inserted",
        },
        {
            settings: {
                foreground: "#ce9178",
            },
            scope: "markup.deleted",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "markup.changed",
        },
        {
            settings: {
                foreground: "#6A9955",
            },
            scope: "punctuation.definition.quote.begin.markdown",
        },
        {
            settings: {
                foreground: "#6796e6",
            },
            scope: "punctuation.definition.list.begin.markdown",
        },
        {
            settings: {
                foreground: "#ce9178",
            },
            scope: "markup.inline.raw",
        },
        {
            settings: {
                foreground: "#808080",
            },
            name: "brackets of XML/HTML tags",
            scope: "punctuation.definition.tag",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: ["meta.preprocessor", "entity.name.function.preprocessor"],
        },
        {
            settings: {
                foreground: "#ce9178",
            },
            scope: "meta.preprocessor.string",
        },
        {
            settings: {
                foreground: "#b5cea8",
            },
            scope: "meta.preprocessor.numeric",
        },
        {
            settings: {
                foreground: "#9cdcfe",
            },
            scope: "meta.structure.dictionary.key.python",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "meta.diff.header",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "storage",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "storage.type",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: ["storage.modifier", "keyword.operator.noexcept"],
        },
        {
            settings: {
                foreground: "#ce9178",
            },
            scope: ["string", "meta.embedded.assembly"],
        },
        {
            settings: {
                foreground: "#ce9178",
            },
            scope: "string.tag",
        },
        {
            settings: {
                foreground: "#ce9178",
            },
            scope: "string.value",
        },
        {
            settings: {
                foreground: "#d16969",
            },
            scope: "string.regexp",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            name: "String interpolation",
            scope: [
                "punctuation.definition.template-expression.begin",
                "punctuation.definition.template-expression.end",
                "punctuation.section.embedded",
            ],
        },
        {
            settings: {
                foreground: "#d4d4d4",
            },
            name: "Reset JavaScript string interpolation expression",
            scope: ["meta.template.expression"],
        },
        {
            settings: {
                foreground: "#9cdcfe",
            },
            scope: [
                "support.type.vendored.property-name",
                "support.type.property-name",
                "source.css variable",
                "source.coffee.embedded",
            ],
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "keyword",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: "keyword.control",
        },
        {
            settings: {
                foreground: "#d4d4d4",
            },
            scope: "keyword.operator",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: [
                "keyword.operator.new",
                "keyword.operator.expression",
                "keyword.operator.cast",
                "keyword.operator.sizeof",
                "keyword.operator.alignof",
                "keyword.operator.typeid",
                "keyword.operator.alignas",
                "keyword.operator.instanceof",
                "keyword.operator.logical.python",
                "keyword.operator.wordlike",
            ],
        },
        {
            settings: {
                foreground: "#b5cea8",
            },
            scope: "keyword.other.unit",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: ["punctuation.section.embedded.begin.php", "punctuation.section.embedded.end.php"],
        },
        {
            settings: {
                foreground: "#9cdcfe",
            },
            scope: "support.function.git-rebase",
        },
        {
            settings: {
                foreground: "#b5cea8",
            },
            scope: "constant.sha.git-rebase",
        },
        {
            settings: {
                foreground: "#d4d4d4",
            },
            name: "coloring of the Java import and package identifiers",
            scope: ["storage.modifier.import.java", "variable.language.wildcard.java", "storage.modifier.package.java"],
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            name: "this.self",
            scope: "variable.language",
        },
        {
            settings: {
                foreground: "#DCDCAA",
            },
            name: "Function declarations",
            scope: [
                "entity.name.function",
                "support.function",
                "support.constant.handlebars",
                "source.powershell variable.other.member",
                "entity.name.operator.custom-literal",
            ],
        },
        {
            settings: {
                foreground: "#4EC9B0",
            },
            name: "Types declaration and references",
            scope: [
                "support.class",
                "support.type",
                "entity.name.type",
                "entity.name.namespace",
                "entity.other.attribute",
                "entity.name.scope-resolution",
                "entity.name.class",
                "storage.type.numeric.go",
                "storage.type.byte.go",
                "storage.type.boolean.go",
                "storage.type.string.go",
                "storage.type.uintptr.go",
                "storage.type.error.go",
                "storage.type.rune.go",
                "storage.type.cs",
                "storage.type.generic.cs",
                "storage.type.modifier.cs",
                "storage.type.variable.cs",
                "storage.type.annotation.java",
                "storage.type.generic.java",
                "storage.type.java",
                "storage.type.object.array.java",
                "storage.type.primitive.array.java",
                "storage.type.primitive.java",
                "storage.type.token.java",
                "storage.type.groovy",
                "storage.type.annotation.groovy",
                "storage.type.parameters.groovy",
                "storage.type.generic.groovy",
                "storage.type.object.array.groovy",
                "storage.type.primitive.array.groovy",
                "storage.type.primitive.groovy",
            ],
        },
        {
            settings: {
                foreground: "#4EC9B0",
            },
            name: "Types declaration and references, TS grammar specific",
            scope: [
                "meta.type.cast.expr",
                "meta.type.new.expr",
                "support.constant.math",
                "support.constant.dom",
                "support.constant.json",
                "entity.other.inherited-class",
                "punctuation.separator.namespace.ruby",
            ],
        },
        {
            settings: {
                foreground: "#C586C0",
            },
            name: "Control flow / Special keywords",
            scope: [
                "keyword.control",
                "source.cpp keyword.operator.new",
                "keyword.operator.delete",
                "keyword.other.using",
                "keyword.other.directive.using",
                "keyword.other.operator",
                "entity.name.operator",
            ],
        },
        {
            settings: {
                foreground: "#9CDCFE",
            },
            name: "Variable and parameter name",
            scope: [
                "variable",
                "meta.definition.variable.name",
                "support.variable",
                "entity.name.variable",
                "constant.other.placeholder",
            ],
        },
        {
            settings: {
                foreground: "#4FC1FF",
            },
            name: "Constants and enums",
            scope: ["variable.other.constant", "variable.other.enummember"],
        },
        {
            settings: {
                foreground: "#9CDCFE",
            },
            name: "Object keys, TS grammar specific",
            scope: ["meta.object-literal.key"],
        },
        {
            settings: {
                foreground: "#CE9178",
            },
            name: "CSS property value",
            scope: [
                "support.constant.property-value",
                "support.constant.font-name",
                "support.constant.media-type",
                "support.constant.media",
                "constant.other.color.rgb-value",
                "constant.other.rgb-value",
                "support.constant.color",
            ],
        },
        {
            settings: {
                foreground: "#CE9178",
            },
            name: "Regular expression groups",
            scope: [
                "punctuation.definition.group.regexp",
                "punctuation.definition.group.assertion.regexp",
                "punctuation.definition.character-class.regexp",
                "punctuation.character.set.begin.regexp",
                "punctuation.character.set.end.regexp",
                "keyword.operator.negation.regexp",
                "support.other.parenthesis.regexp",
            ],
        },
        {
            settings: {
                foreground: "#d16969",
            },
            scope: [
                "constant.character.character-class.regexp",
                "constant.other.character-class.set.regexp",
                "constant.other.character-class.regexp",
                "constant.character.set.regexp",
            ],
        },
        {
            settings: {
                foreground: "#DCDCAA",
            },
            scope: ["keyword.operator.or.regexp", "keyword.control.anchor.regexp"],
        },
        {
            settings: {
                foreground: "#d7ba7d",
            },
            scope: "keyword.operator.quantifier.regexp",
        },
        {
            settings: {
                foreground: "#569cd6",
            },
            scope: ["constant.character", "constant.other.option"],
        },
        {
            settings: {
                foreground: "#d7ba7d",
            },
            scope: "constant.character.escape",
        },
        {
            settings: {
                foreground: "#C8C8C8",
            },
            scope: "entity.name.label",
        },
        {
            settings: {
                foreground: "#8b949e",
            },
            scope: ["comment", "punctuation.definition.comment", "string.comment"],
        },
        {
            settings: {
                foreground: "#ff7b72",
            },
            scope: ["constant.other.placeholder", "constant.character"],
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: [
                "constant",
                "entity.name.constant",
                "variable.other.constant",
                "variable.other.enummember",
                "variable.language",
                "entity",
            ],
        },
        {
            settings: {
                foreground: "#ffa657",
            },
            scope: ["entity.name", "meta.export.default", "meta.definition.variable"],
        },
        {
            settings: {
                foreground: "#c9d1d9",
            },
            scope: [
                "variable.parameter.function",
                "meta.jsx.children",
                "meta.block",
                "meta.tag.attributes",
                "entity.name.constant",
                "meta.object.member",
                "meta.embedded.expression",
            ],
        },
        {
            settings: {
                foreground: "#d2a8ff",
            },
            scope: "entity.name.function",
        },
        {
            settings: {
                foreground: "#7ee787",
            },
            scope: ["entity.name.tag", "support.class.component"],
        },
        {
            settings: {
                foreground: "#ff7b72",
            },
            scope: "keyword",
        },
        {
            settings: {
                foreground: "#ff7b72",
            },
            scope: ["storage", "storage.type"],
        },
        {
            settings: {
                foreground: "#c9d1d9",
            },
            scope: ["storage.modifier.package", "storage.modifier.import", "storage.type.java"],
        },
        {
            settings: {
                foreground: "#a5d6ff",
            },
            scope: ["string", "string punctuation.section.embedded source"],
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "support",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "meta.property-name",
        },
        {
            settings: {
                foreground: "#ffa657",
            },
            scope: "variable",
        },
        {
            settings: {
                foreground: "#c9d1d9",
            },
            scope: "variable.other",
        },
        {
            settings: {
                foreground: "#ffa198",
                fontStyle: "italic",
            },
            scope: "invalid.broken",
        },
        {
            settings: {
                foreground: "#ffa198",
                fontStyle: "italic",
            },
            scope: "invalid.deprecated",
        },
        {
            settings: {
                foreground: "#ffa198",
                fontStyle: "italic",
            },
            scope: "invalid.illegal",
        },
        {
            settings: {
                foreground: "#ffa198",
                fontStyle: "italic",
            },
            scope: "invalid.unimplemented",
        },
        {
            settings: {
                foreground: "#f0f6fc",
                background: "#8b1111",
                fontStyle: "italic underline",
            },
            scope: "carriage-return",
        },
        {
            settings: {
                foreground: "#ffa198",
            },
            scope: "message.error",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "string variable",
        },
        {
            settings: {
                foreground: "#a5d6ff",
            },
            scope: ["source.regexp", "string.regexp"],
        },
        {
            settings: {
                foreground: "#a5d6ff",
            },
            scope: [
                "string.regexp.character-class",
                "string.regexp constant.character.escape",
                "string.regexp source.ruby.embedded",
                "string.regexp string.regexp.arbitrary-repitition",
            ],
        },
        {
            settings: {
                foreground: "#7ee787",
                fontStyle: "bold",
            },
            scope: "string.regexp constant.character.escape",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "support.constant",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "support.variable",
        },
        {
            settings: {
                foreground: "#7ee787",
            },
            scope: "support.type.property-name.json",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "meta.module-reference",
        },
        {
            settings: {
                foreground: "#ffa657",
            },
            scope: "punctuation.definition.list.begin.markdown",
        },
        {
            settings: {
                foreground: "#79c0ff",
                fontStyle: "bold",
            },
            scope: ["markup.heading", "markup.heading entity.name"],
        },
        {
            settings: {
                foreground: "#7ee787",
            },
            scope: "markup.quote",
        },
        {
            settings: {
                foreground: "#c9d1d9",
                fontStyle: "italic",
            },
            scope: "markup.italic",
        },
        {
            settings: {
                foreground: "#c9d1d9",
                fontStyle: "bold",
            },
            scope: "markup.bold",
        },
        {
            settings: {
                fontStyle: "underline",
            },
            scope: ["markup.underline"],
        },
        {
            settings: {
                fontStyle: "strikethrough",
            },
            scope: ["markup.strikethrough"],
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "markup.inline.raw",
        },
        {
            settings: {
                foreground: "#ffa198",
                background: "#490202",
            },
            scope: ["markup.deleted", "meta.diff.header.from-file", "punctuation.definition.deleted"],
        },
        {
            settings: {
                foreground: "#ff7b72",
            },
            scope: ["punctuation.section.embedded"],
        },
        {
            settings: {
                foreground: "#7ee787",
                background: "#04260f",
            },
            scope: ["markup.inserted", "meta.diff.header.to-file", "punctuation.definition.inserted"],
        },
        {
            settings: {
                foreground: "#ffa657",
                background: "#5a1e02",
            },
            scope: ["markup.changed", "punctuation.definition.changed"],
        },
        {
            settings: {
                foreground: "#0d1117",
                background: "#79c0ff",
            },
            scope: ["markup.ignored", "markup.untracked"],
        },
        {
            settings: {
                foreground: "#d2a8ff",
                fontStyle: "bold",
            },
            scope: "meta.diff.range",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "meta.diff.header",
        },
        {
            settings: {
                foreground: "#79c0ff",
                fontStyle: "bold",
            },
            scope: "meta.separator",
        },
        {
            settings: {
                foreground: "#79c0ff",
            },
            scope: "meta.output",
        },
        {
            settings: {
                foreground: "#8b949e",
            },
            scope: [
                "brackethighlighter.tag",
                "brackethighlighter.curly",
                "brackethighlighter.round",
                "brackethighlighter.square",
                "brackethighlighter.angle",
                "brackethighlighter.quote",
            ],
        },
        {
            settings: {
                foreground: "#ffa198",
            },
            scope: "brackethighlighter.unmatched",
        },
        {
            settings: {
                foreground: "#a5d6ff",
            },
            scope: ["constant.other.reference.link", "string.other.link"],
        },
        {
            settings: {
                foreground: "#6796E6",
            },
            scope: "token.info-token",
        },
        {
            settings: {
                foreground: "#CD9731",
            },
            scope: "token.warn-token",
        },
        {
            settings: {
                foreground: "#F44747",
            },
            scope: "token.error-token",
        },
        {
            settings: {
                foreground: "#B267E6",
            },
            scope: "token.debug-token",
        },
    ],
};
