// GENERATED by scripts/import-vscode-themes.mjs from microsoft/vscode 1.127.0.
// Do not edit by hand — re-run the script to refresh.
import type { IThemeFile } from "../IThemeFile.ts";

export const darkModernTheme: IThemeFile = {
    "name": "Dark Modern",
    "type": "dark",
    "colors": {
        "checkbox.border": "#3C3C3C",
        "editor.background": "#1F1F1F",
        "editor.foreground": "#CCCCCC",
        "editor.inactiveSelectionBackground": "#3A3D41",
        "editorIndentGuide.background1": "#404040",
        "editorIndentGuide.activeBackground1": "#707070",
        "editor.selectionHighlightBackground": "#ADD6FF26",
        "list.dropBackground": "#383B3D",
        "activityBarBadge.background": "#0078D4",
        "sideBarTitle.foreground": "#CCCCCC",
        "input.placeholderForeground": "#989898",
        "menu.background": "#1F1F1F",
        "menu.foreground": "#CCCCCC",
        "menu.separatorBackground": "#454545",
        "menu.border": "#454545",
        "menu.selectionBackground": "#0078d4",
        "statusBarItem.remoteForeground": "#FFFFFF",
        "statusBarItem.remoteBackground": "#0078D4",
        "ports.iconRunningProcessForeground": "#369432",
        "sideBarSectionHeader.background": "#181818",
        "sideBarSectionHeader.border": "#2B2B2B",
        "tab.selectedBackground": "#222222",
        "tab.selectedForeground": "#ffffffa0",
        "tab.lastPinnedBorder": "#ccc3",
        "list.activeSelectionIconForeground": "#FFF",
        "terminal.inactiveSelectionBackground": "#3A3D41",
        "widget.border": "#313131",
        "actionBar.toggledBackground": "#383a49",
        "agentsPanel.border": "#303031",
        "agentsChatInput.border": "#303031",
        "agentsChatInput.focusBorder": "#007ACC",
        "agentsNewSessionButton.border": "#303031",
        "activityBar.activeBorder": "#0078D4",
        "activityBar.background": "#181818",
        "activityBar.border": "#2B2B2B",
        "activityBar.foreground": "#D7D7D7",
        "activityBar.inactiveForeground": "#868686",
        "activityBarBadge.foreground": "#FFFFFF",
        "badge.background": "#616161",
        "badge.foreground": "#F8F8F8",
        "button.background": "#0078D4",
        "button.border": "#ffffff1a",
        "button.foreground": "#FFFFFF",
        "button.hoverBackground": "#026EC1",
        "button.secondaryBackground": "#00000000",
        "button.secondaryForeground": "#CCCCCC",
        "button.secondaryHoverBackground": "#2B2B2B",
        "chat.slashCommandBackground": "#26477866",
        "chat.slashCommandForeground": "#85B6FF",
        "chat.editedFileForeground": "#E2C08D",
        "checkbox.background": "#313131",
        "debugToolBar.background": "#181818",
        "descriptionForeground": "#9D9D9D",
        "dropdown.background": "#313131",
        "dropdown.border": "#3C3C3C",
        "dropdown.foreground": "#CCCCCC",
        "dropdown.listBackground": "#1F1F1F",
        "editor.findMatchBackground": "#9E6A03",
        "editorGroup.border": "#FFFFFF17",
        "editorGroupHeader.tabsBackground": "#181818",
        "editorGroupHeader.tabsBorder": "#2B2B2B",
        "editorGutter.addedBackground": "#2EA043",
        "editorGutter.deletedBackground": "#F85149",
        "editorGutter.modifiedBackground": "#0078D4",
        "editorLineNumber.activeForeground": "#CCCCCC",
        "editorLineNumber.foreground": "#6E7681",
        "editorOverviewRuler.border": "#010409",
        "editorWidget.background": "#202020",
        "errorForeground": "#F85149",
        "focusBorder": "#0078D4",
        "foreground": "#CCCCCC",
        "icon.foreground": "#CCCCCC",
        "input.background": "#313131",
        "input.border": "#3C3C3C",
        "input.foreground": "#CCCCCC",
        "inputOption.activeBackground": "#2489DB82",
        "inputOption.activeBorder": "#2488DB",
        "keybindingLabel.foreground": "#CCCCCC",
        "notificationCenterHeader.background": "#1F1F1F",
        "notificationCenterHeader.foreground": "#CCCCCC",
        "notifications.background": "#1F1F1F",
        "notifications.border": "#2B2B2B",
        "notifications.foreground": "#CCCCCC",
        "panel.background": "#181818",
        "panel.border": "#2B2B2B",
        "panelInput.border": "#2B2B2B",
        "panelTitle.activeBorder": "#0078D4",
        "panelTitle.activeForeground": "#CCCCCC",
        "panelTitle.inactiveForeground": "#9D9D9D",
        "peekViewEditor.background": "#1F1F1F",
        "peekViewEditor.matchHighlightBackground": "#BB800966",
        "peekViewResult.background": "#1F1F1F",
        "peekViewResult.matchHighlightBackground": "#BB800966",
        "pickerGroup.border": "#3C3C3C",
        "progressBar.background": "#0078D4",
        "quickInput.background": "#222222",
        "quickInput.foreground": "#CCCCCC",
        "settings.dropdownBackground": "#313131",
        "settings.dropdownBorder": "#3C3C3C",
        "settings.headerForeground": "#FFFFFF",
        "settings.modifiedItemIndicator": "#BB800966",
        "sideBar.background": "#181818",
        "sideBar.border": "#2B2B2B",
        "sideBar.foreground": "#CCCCCC",
        "sideBarSectionHeader.foreground": "#CCCCCC",
        "statusBar.background": "#181818",
        "statusBar.border": "#2B2B2B",
        "statusBarItem.hoverBackground": "#F1F1F133",
        "statusBarItem.hoverForeground": "#FFFFFF",
        "statusBar.debuggingBackground": "#0078D4",
        "statusBar.debuggingForeground": "#FFFFFF",
        "statusBar.focusBorder": "#0078D4",
        "statusBar.foreground": "#CCCCCC",
        "statusBar.noFolderBackground": "#1F1F1F",
        "statusBarItem.focusBorder": "#0078D4",
        "statusBarItem.prominentBackground": "#6E768166",
        "tab.activeBackground": "#1F1F1F",
        "tab.activeBorder": "#1F1F1F",
        "tab.activeBorderTop": "#0078D4",
        "tab.activeForeground": "#FFFFFF",
        "tab.selectedBorderTop": "#6caddf",
        "tab.border": "#2B2B2B",
        "tab.hoverBackground": "#1F1F1F",
        "tab.inactiveBackground": "#181818",
        "tab.inactiveForeground": "#9D9D9D",
        "tab.unfocusedActiveBorder": "#1F1F1F",
        "tab.unfocusedActiveBorderTop": "#2B2B2B",
        "tab.unfocusedHoverBackground": "#1F1F1F",
        "terminal.foreground": "#CCCCCC",
        "terminal.tab.activeBorder": "#0078D4",
        "textBlockQuote.background": "#2B2B2B",
        "textBlockQuote.border": "#616161",
        "textCodeBlock.background": "#2B2B2B",
        "textLink.activeForeground": "#4daafc",
        "textLink.foreground": "#4daafc",
        "textPreformat.foreground": "#D0D0D0",
        "textPreformat.background": "#3C3C3C",
        "textSeparator.foreground": "#21262D",
        "titleBar.activeBackground": "#181818",
        "titleBar.activeForeground": "#CCCCCC",
        "titleBar.border": "#2B2B2B",
        "titleBar.inactiveBackground": "#1F1F1F",
        "titleBar.inactiveForeground": "#9D9D9D",
        "welcomePage.tileBackground": "#2B2B2B",
        "welcomePage.progress.foreground": "#0078D4"
    },
    "tokenColors": [
        {
            "settings": {
                "foreground": "#D4D4D4"
            },
            "scope": [
                "meta.embedded",
                "source.groovy.embedded",
                "string meta.image.inline.markdown",
                "variable.legacy.builtin.python"
            ]
        },
        {
            "settings": {
                "fontStyle": "italic"
            },
            "scope": "emphasis"
        },
        {
            "settings": {
                "fontStyle": "bold"
            },
            "scope": "strong"
        },
        {
            "settings": {
                "foreground": "#000080"
            },
            "scope": "header"
        },
        {
            "settings": {
                "foreground": "#6A9955"
            },
            "scope": "comment"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "constant.language"
        },
        {
            "settings": {
                "foreground": "#b5cea8"
            },
            "scope": [
                "constant.numeric",
                "variable.other.enummember",
                "keyword.operator.plus.exponent",
                "keyword.operator.minus.exponent"
            ]
        },
        {
            "settings": {
                "foreground": "#646695"
            },
            "scope": "constant.regexp"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "entity.name.tag"
        },
        {
            "settings": {
                "foreground": "#d7ba7d"
            },
            "scope": [
                "entity.name.tag.css",
                "entity.name.tag.less"
            ]
        },
        {
            "settings": {
                "foreground": "#9cdcfe"
            },
            "scope": "entity.other.attribute-name"
        },
        {
            "settings": {
                "foreground": "#d7ba7d"
            },
            "scope": [
                "entity.other.attribute-name.class.css",
                "source.css entity.other.attribute-name.class",
                "entity.other.attribute-name.id.css",
                "entity.other.attribute-name.parent-selector.css",
                "entity.other.attribute-name.parent.less",
                "source.css entity.other.attribute-name.pseudo-class",
                "entity.other.attribute-name.pseudo-element.css",
                "source.css.less entity.other.attribute-name.id",
                "entity.other.attribute-name.scss"
            ]
        },
        {
            "settings": {
                "foreground": "#f44747"
            },
            "scope": "invalid"
        },
        {
            "settings": {
                "fontStyle": "underline"
            },
            "scope": "markup.underline"
        },
        {
            "settings": {
                "foreground": "#569cd6",
                "fontStyle": "bold"
            },
            "scope": "markup.bold"
        },
        {
            "settings": {
                "foreground": "#569cd6",
                "fontStyle": "bold"
            },
            "scope": "markup.heading"
        },
        {
            "settings": {
                "foreground": "#C586C0",
                "fontStyle": "italic"
            },
            "scope": "markup.italic"
        },
        {
            "settings": {
                "fontStyle": "strikethrough"
            },
            "scope": "markup.strikethrough"
        },
        {
            "settings": {
                "foreground": "#b5cea8"
            },
            "scope": "markup.inserted"
        },
        {
            "settings": {
                "foreground": "#ce9178"
            },
            "scope": "markup.deleted"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "markup.changed"
        },
        {
            "settings": {
                "foreground": "#6A9955"
            },
            "scope": "punctuation.definition.quote.begin.markdown"
        },
        {
            "settings": {
                "foreground": "#6796e6"
            },
            "scope": "punctuation.definition.list.begin.markdown"
        },
        {
            "settings": {
                "foreground": "#ce9178"
            },
            "scope": "markup.inline.raw"
        },
        {
            "settings": {
                "foreground": "#808080"
            },
            "name": "brackets of XML/HTML tags",
            "scope": "punctuation.definition.tag"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": [
                "meta.preprocessor",
                "entity.name.function.preprocessor"
            ]
        },
        {
            "settings": {
                "foreground": "#ce9178"
            },
            "scope": "meta.preprocessor.string"
        },
        {
            "settings": {
                "foreground": "#b5cea8"
            },
            "scope": "meta.preprocessor.numeric"
        },
        {
            "settings": {
                "foreground": "#9cdcfe"
            },
            "scope": "meta.structure.dictionary.key.python"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "meta.diff.header"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "storage"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "storage.type"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": [
                "storage.modifier",
                "keyword.operator.noexcept"
            ]
        },
        {
            "settings": {
                "foreground": "#ce9178"
            },
            "scope": [
                "string",
                "meta.embedded.assembly"
            ]
        },
        {
            "settings": {
                "foreground": "#ce9178"
            },
            "scope": "string.tag"
        },
        {
            "settings": {
                "foreground": "#ce9178"
            },
            "scope": "string.value"
        },
        {
            "settings": {
                "foreground": "#d16969"
            },
            "scope": "string.regexp"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "name": "String interpolation",
            "scope": [
                "punctuation.definition.template-expression.begin",
                "punctuation.definition.template-expression.end",
                "punctuation.section.embedded"
            ]
        },
        {
            "settings": {
                "foreground": "#d4d4d4"
            },
            "name": "Reset JavaScript string interpolation expression",
            "scope": [
                "meta.template.expression"
            ]
        },
        {
            "settings": {
                "foreground": "#9cdcfe"
            },
            "scope": [
                "support.type.vendored.property-name",
                "support.type.property-name",
                "source.css variable",
                "source.coffee.embedded"
            ]
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "keyword"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": "keyword.control"
        },
        {
            "settings": {
                "foreground": "#d4d4d4"
            },
            "scope": "keyword.operator"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": [
                "keyword.operator.new",
                "keyword.operator.expression",
                "keyword.operator.cast",
                "keyword.operator.sizeof",
                "keyword.operator.alignof",
                "keyword.operator.typeid",
                "keyword.operator.alignas",
                "keyword.operator.instanceof",
                "keyword.operator.logical.python",
                "keyword.operator.wordlike"
            ]
        },
        {
            "settings": {
                "foreground": "#b5cea8"
            },
            "scope": "keyword.other.unit"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": [
                "punctuation.section.embedded.begin.php",
                "punctuation.section.embedded.end.php"
            ]
        },
        {
            "settings": {
                "foreground": "#9cdcfe"
            },
            "scope": "support.function.git-rebase"
        },
        {
            "settings": {
                "foreground": "#b5cea8"
            },
            "scope": "constant.sha.git-rebase"
        },
        {
            "settings": {
                "foreground": "#d4d4d4"
            },
            "name": "coloring of the Java import and package identifiers",
            "scope": [
                "storage.modifier.import.java",
                "variable.language.wildcard.java",
                "storage.modifier.package.java"
            ]
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "name": "this.self",
            "scope": "variable.language"
        },
        {
            "settings": {
                "foreground": "#DCDCAA"
            },
            "name": "Function declarations",
            "scope": [
                "entity.name.function",
                "support.function",
                "support.constant.handlebars",
                "source.powershell variable.other.member",
                "entity.name.operator.custom-literal"
            ]
        },
        {
            "settings": {
                "foreground": "#4EC9B0"
            },
            "name": "Types declaration and references",
            "scope": [
                "support.class",
                "support.type",
                "entity.name.type",
                "entity.name.namespace",
                "entity.other.attribute",
                "entity.name.scope-resolution",
                "entity.name.class",
                "storage.type.numeric.go",
                "storage.type.byte.go",
                "storage.type.boolean.go",
                "storage.type.string.go",
                "storage.type.uintptr.go",
                "storage.type.error.go",
                "storage.type.rune.go",
                "storage.type.cs",
                "storage.type.generic.cs",
                "storage.type.modifier.cs",
                "storage.type.variable.cs",
                "storage.type.annotation.java",
                "storage.type.generic.java",
                "storage.type.java",
                "storage.type.object.array.java",
                "storage.type.primitive.array.java",
                "storage.type.primitive.java",
                "storage.type.token.java",
                "storage.type.groovy",
                "storage.type.annotation.groovy",
                "storage.type.parameters.groovy",
                "storage.type.generic.groovy",
                "storage.type.object.array.groovy",
                "storage.type.primitive.array.groovy",
                "storage.type.primitive.groovy"
            ]
        },
        {
            "settings": {
                "foreground": "#4EC9B0"
            },
            "name": "Types declaration and references, TS grammar specific",
            "scope": [
                "meta.type.cast.expr",
                "meta.type.new.expr",
                "support.constant.math",
                "support.constant.dom",
                "support.constant.json",
                "entity.other.inherited-class",
                "punctuation.separator.namespace.ruby"
            ]
        },
        {
            "settings": {
                "foreground": "#C586C0"
            },
            "name": "Control flow / Special keywords",
            "scope": [
                "keyword.control",
                "source.cpp keyword.operator.new",
                "keyword.operator.delete",
                "keyword.other.using",
                "keyword.other.directive.using",
                "keyword.other.operator",
                "entity.name.operator"
            ]
        },
        {
            "settings": {
                "foreground": "#9CDCFE"
            },
            "name": "Variable and parameter name",
            "scope": [
                "variable",
                "meta.definition.variable.name",
                "support.variable",
                "entity.name.variable",
                "constant.other.placeholder"
            ]
        },
        {
            "settings": {
                "foreground": "#4FC1FF"
            },
            "name": "Constants and enums",
            "scope": [
                "variable.other.constant",
                "variable.other.enummember"
            ]
        },
        {
            "settings": {
                "foreground": "#9CDCFE"
            },
            "name": "Object keys, TS grammar specific",
            "scope": [
                "meta.object-literal.key"
            ]
        },
        {
            "settings": {
                "foreground": "#CE9178"
            },
            "name": "CSS property value",
            "scope": [
                "support.constant.property-value",
                "support.constant.font-name",
                "support.constant.media-type",
                "support.constant.media",
                "constant.other.color.rgb-value",
                "constant.other.rgb-value",
                "support.constant.color"
            ]
        },
        {
            "settings": {
                "foreground": "#CE9178"
            },
            "name": "Regular expression groups",
            "scope": [
                "punctuation.definition.group.regexp",
                "punctuation.definition.group.assertion.regexp",
                "punctuation.definition.character-class.regexp",
                "punctuation.character.set.begin.regexp",
                "punctuation.character.set.end.regexp",
                "keyword.operator.negation.regexp",
                "support.other.parenthesis.regexp"
            ]
        },
        {
            "settings": {
                "foreground": "#d16969"
            },
            "scope": [
                "constant.character.character-class.regexp",
                "constant.other.character-class.set.regexp",
                "constant.other.character-class.regexp",
                "constant.character.set.regexp"
            ]
        },
        {
            "settings": {
                "foreground": "#DCDCAA"
            },
            "scope": [
                "keyword.operator.or.regexp",
                "keyword.control.anchor.regexp"
            ]
        },
        {
            "settings": {
                "foreground": "#d7ba7d"
            },
            "scope": "keyword.operator.quantifier.regexp"
        },
        {
            "settings": {
                "foreground": "#569cd6"
            },
            "scope": [
                "constant.character",
                "constant.other.option"
            ]
        },
        {
            "settings": {
                "foreground": "#d7ba7d"
            },
            "scope": "constant.character.escape"
        },
        {
            "settings": {
                "foreground": "#C8C8C8"
            },
            "scope": "entity.name.label"
        }
    ]
};
