// GENERATED by scripts/import-vscode-themes.mjs from microsoft/vscode 1.127.0.
// Do not edit by hand — re-run the script to refresh.
import type { IThemeFile } from "../IThemeFile.ts";

export const lightModernTheme: IThemeFile = {
    "name": "Light Modern",
    "type": "light",
    "colors": {
        "checkbox.border": "#CECECE",
        "editor.background": "#FFFFFF",
        "editor.foreground": "#3B3B3B",
        "editor.inactiveSelectionBackground": "#E5EBF1",
        "editorIndentGuide.background1": "#D3D3D3",
        "editorIndentGuide.activeBackground1": "#939393",
        "editor.selectionHighlightBackground": "#ADD6FF80",
        "editorSuggestWidget.background": "#F8F8F8",
        "activityBarBadge.background": "#005FB8",
        "sideBarTitle.foreground": "#3B3B3B",
        "list.hoverBackground": "#F2F2F2",
        "menu.border": "#CECECE",
        "input.placeholderForeground": "#767676",
        "searchEditor.textInputBorder": "#CECECE",
        "settings.textInputBorder": "#CECECE",
        "settings.numberInputBorder": "#CECECE",
        "statusBarItem.remoteForeground": "#FFFFFF",
        "statusBarItem.remoteBackground": "#005FB8",
        "ports.iconRunningProcessForeground": "#369432",
        "sideBarSectionHeader.background": "#F8F8F8",
        "sideBarSectionHeader.border": "#E5E5E5",
        "tab.selectedForeground": "#333333b3",
        "tab.selectedBackground": "#ffffffa5",
        "tab.lastPinnedBorder": "#D4D4D4",
        "notebook.cellBorderColor": "#E5E5E5",
        "notebook.selectedCellBackground": "#C8DDF150",
        "statusBarItem.errorBackground": "#C72E0F",
        "list.activeSelectionIconForeground": "#000000",
        "list.focusAndSelectionOutline": "#005FB8",
        "terminal.inactiveSelectionBackground": "#E5EBF1",
        "widget.border": "#E5E5E5",
        "actionBar.toggledBackground": "#dddddd",
        "diffEditor.unchangedRegionBackground": "#f8f8f8",
        "agentsNewSessionButton.border": "#D8D8D8",
        "agentsChatInput.border": "#D8D8D8",
        "activityBar.activeBorder": "#005FB8",
        "activityBar.background": "#F8F8F8",
        "activityBar.border": "#E5E5E5",
        "activityBar.foreground": "#1F1F1F",
        "activityBar.inactiveForeground": "#616161",
        "activityBarBadge.foreground": "#FFFFFF",
        "badge.background": "#CCCCCC",
        "badge.foreground": "#3B3B3B",
        "button.background": "#005FB8",
        "button.border": "#0000001a",
        "button.foreground": "#FFFFFF",
        "button.hoverBackground": "#0258A8",
        "button.secondaryBackground": "#E5E5E5",
        "button.secondaryForeground": "#3B3B3B",
        "button.secondaryHoverBackground": "#CCCCCC",
        "chat.slashCommandBackground": "#ADCEFF7A",
        "chat.slashCommandForeground": "#26569E",
        "chat.editedFileForeground": "#895503",
        "checkbox.background": "#F8F8F8",
        "descriptionForeground": "#3B3B3B",
        "dropdown.background": "#FFFFFF",
        "dropdown.border": "#CECECE",
        "dropdown.foreground": "#3B3B3B",
        "dropdown.listBackground": "#FFFFFF",
        "editorGroup.border": "#E5E5E5",
        "editorGroupHeader.tabsBackground": "#F8F8F8",
        "editorGroupHeader.tabsBorder": "#E5E5E5",
        "editorGutter.addedBackground": "#2EA043",
        "editorGutter.deletedBackground": "#F85149",
        "editorGutter.modifiedBackground": "#005FB8",
        "editorLineNumber.activeForeground": "#171184",
        "editorLineNumber.foreground": "#6E7681",
        "editorOverviewRuler.border": "#E5E5E5",
        "editorWidget.background": "#F8F8F8",
        "errorForeground": "#F85149",
        "focusBorder": "#005FB8",
        "foreground": "#3B3B3B",
        "icon.foreground": "#3B3B3B",
        "input.background": "#FFFFFF",
        "input.border": "#CECECE",
        "input.foreground": "#3B3B3B",
        "inputOption.activeBackground": "#BED6ED",
        "inputOption.activeBorder": "#005FB8",
        "inputOption.activeForeground": "#000000",
        "keybindingLabel.foreground": "#3B3B3B",
        "list.activeSelectionBackground": "#E8E8E8",
        "list.activeSelectionForeground": "#000000",
        "menu.selectionBackground": "#005FB8",
        "menu.selectionForeground": "#ffffff",
        "notificationCenterHeader.background": "#FFFFFF",
        "notificationCenterHeader.foreground": "#3B3B3B",
        "notifications.background": "#FFFFFF",
        "notifications.border": "#E5E5E5",
        "notifications.foreground": "#3B3B3B",
        "panel.background": "#F8F8F8",
        "panel.border": "#E5E5E5",
        "panelInput.border": "#E5E5E5",
        "panelTitle.activeBorder": "#005FB8",
        "panelTitle.activeForeground": "#3B3B3B",
        "panelTitle.inactiveForeground": "#3B3B3B",
        "peekViewEditor.matchHighlightBackground": "#BB800966",
        "peekViewResult.background": "#FFFFFF",
        "peekViewResult.matchHighlightBackground": "#BB800966",
        "pickerGroup.border": "#E5E5E5",
        "pickerGroup.foreground": "#8B949E",
        "progressBar.background": "#005FB8",
        "quickInput.background": "#F8F8F8",
        "quickInput.foreground": "#3B3B3B",
        "settings.dropdownBackground": "#FFFFFF",
        "settings.dropdownBorder": "#CECECE",
        "settings.headerForeground": "#1F1F1F",
        "settings.modifiedItemIndicator": "#BB800966",
        "sideBar.background": "#F8F8F8",
        "sideBar.border": "#E5E5E5",
        "sideBar.foreground": "#3B3B3B",
        "sideBarSectionHeader.foreground": "#3B3B3B",
        "statusBar.background": "#F8F8F8",
        "statusBar.foreground": "#3B3B3B",
        "statusBar.border": "#E5E5E5",
        "statusBarItem.hoverBackground": "#1F1F1F11",
        "statusBarItem.hoverForeground": "#000000",
        "statusBarItem.compactHoverBackground": "#CCCCCC",
        "statusBar.debuggingBackground": "#FD716C",
        "statusBar.debuggingForeground": "#000000",
        "statusBar.focusBorder": "#005FB8",
        "statusBar.noFolderBackground": "#F8F8F8",
        "statusBarItem.focusBorder": "#005FB8",
        "statusBarItem.prominentBackground": "#6E768166",
        "tab.activeBackground": "#FFFFFF",
        "tab.activeBorder": "#F8F8F8",
        "tab.activeBorderTop": "#005FB8",
        "tab.activeForeground": "#3B3B3B",
        "tab.selectedBorderTop": "#68a3da",
        "tab.border": "#E5E5E5",
        "tab.hoverBackground": "#FFFFFF",
        "tab.inactiveBackground": "#F8F8F8",
        "tab.inactiveForeground": "#868686",
        "tab.unfocusedActiveBorder": "#F8F8F8",
        "tab.unfocusedActiveBorderTop": "#E5E5E5",
        "tab.unfocusedHoverBackground": "#F8F8F8",
        "terminalCursor.foreground": "#005FB8",
        "terminal.foreground": "#3B3B3B",
        "terminal.tab.activeBorder": "#005FB8",
        "textBlockQuote.background": "#F8F8F8",
        "textBlockQuote.border": "#E5E5E5",
        "textCodeBlock.background": "#F8F8F8",
        "textLink.activeForeground": "#005FB8",
        "textLink.foreground": "#005FB8",
        "textPreformat.foreground": "#3B3B3B",
        "textPreformat.background": "#0000001F",
        "textSeparator.foreground": "#21262D",
        "titleBar.activeBackground": "#F8F8F8",
        "titleBar.activeForeground": "#1E1E1E",
        "titleBar.border": "#E5E5E5",
        "titleBar.inactiveBackground": "#F8F8F8",
        "titleBar.inactiveForeground": "#8B949E",
        "welcomePage.tileBackground": "#F3F3F3"
    },
    "tokenColors": [
        {
            "settings": {
                "foreground": "#000000ff"
            },
            "scope": [
                "meta.embedded",
                "source.groovy.embedded",
                "string meta.image.inline.markdown",
                "variable.legacy.builtin.python"
            ]
        },
        {
            "settings": {
                "fontStyle": "italic"
            },
            "scope": "emphasis"
        },
        {
            "settings": {
                "fontStyle": "bold"
            },
            "scope": "strong"
        },
        {
            "settings": {
                "foreground": "#000080"
            },
            "scope": "meta.diff.header"
        },
        {
            "settings": {
                "foreground": "#008000"
            },
            "scope": "comment"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": "constant.language"
        },
        {
            "settings": {
                "foreground": "#098658"
            },
            "scope": [
                "constant.numeric",
                "variable.other.enummember",
                "keyword.operator.plus.exponent",
                "keyword.operator.minus.exponent"
            ]
        },
        {
            "settings": {
                "foreground": "#811f3f"
            },
            "scope": "constant.regexp"
        },
        {
            "settings": {
                "foreground": "#800000"
            },
            "name": "css tags in selectors, xml tags",
            "scope": "entity.name.tag"
        },
        {
            "settings": {
                "foreground": "#800000"
            },
            "scope": "entity.name.selector"
        },
        {
            "settings": {
                "foreground": "#e50000"
            },
            "scope": "entity.other.attribute-name"
        },
        {
            "settings": {
                "foreground": "#800000"
            },
            "scope": [
                "entity.other.attribute-name.class.css",
                "source.css entity.other.attribute-name.class",
                "entity.other.attribute-name.id.css",
                "entity.other.attribute-name.parent-selector.css",
                "entity.other.attribute-name.parent.less",
                "source.css entity.other.attribute-name.pseudo-class",
                "entity.other.attribute-name.pseudo-element.css",
                "source.css.less entity.other.attribute-name.id",
                "entity.other.attribute-name.scss"
            ]
        },
        {
            "settings": {
                "foreground": "#cd3131"
            },
            "scope": "invalid"
        },
        {
            "settings": {
                "fontStyle": "underline"
            },
            "scope": "markup.underline"
        },
        {
            "settings": {
                "foreground": "#000080",
                "fontStyle": "bold"
            },
            "scope": "markup.bold"
        },
        {
            "settings": {
                "foreground": "#800000",
                "fontStyle": "bold"
            },
            "scope": "markup.heading"
        },
        {
            "settings": {
                "foreground": "#800080",
                "fontStyle": "italic"
            },
            "scope": "markup.italic"
        },
        {
            "settings": {
                "fontStyle": "strikethrough"
            },
            "scope": "markup.strikethrough"
        },
        {
            "settings": {
                "foreground": "#098658"
            },
            "scope": "markup.inserted"
        },
        {
            "settings": {
                "foreground": "#a31515"
            },
            "scope": "markup.deleted"
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "scope": "markup.changed"
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "scope": [
                "punctuation.definition.quote.begin.markdown",
                "punctuation.definition.list.begin.markdown"
            ]
        },
        {
            "settings": {
                "foreground": "#800000"
            },
            "scope": "markup.inline.raw"
        },
        {
            "settings": {
                "foreground": "#800000"
            },
            "name": "brackets of XML/HTML tags",
            "scope": "punctuation.definition.tag"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": [
                "meta.preprocessor",
                "entity.name.function.preprocessor"
            ]
        },
        {
            "settings": {
                "foreground": "#a31515"
            },
            "scope": "meta.preprocessor.string"
        },
        {
            "settings": {
                "foreground": "#098658"
            },
            "scope": "meta.preprocessor.numeric"
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "scope": "meta.structure.dictionary.key.python"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": "storage"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": "storage.type"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": [
                "storage.modifier",
                "keyword.operator.noexcept"
            ]
        },
        {
            "settings": {
                "foreground": "#a31515"
            },
            "scope": [
                "string",
                "meta.embedded.assembly"
            ]
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": [
                "string.comment.buffered.block.pug",
                "string.quoted.pug",
                "string.interpolated.pug",
                "string.unquoted.plain.in.yaml",
                "string.unquoted.plain.out.yaml",
                "string.unquoted.block.yaml",
                "string.quoted.single.yaml",
                "string.quoted.double.xml",
                "string.quoted.single.xml",
                "string.unquoted.cdata.xml",
                "string.quoted.double.html",
                "string.quoted.single.html",
                "string.unquoted.html",
                "string.quoted.single.handlebars",
                "string.quoted.double.handlebars"
            ]
        },
        {
            "settings": {
                "foreground": "#811f3f"
            },
            "scope": "string.regexp"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "name": "String interpolation",
            "scope": [
                "punctuation.definition.template-expression.begin",
                "punctuation.definition.template-expression.end",
                "punctuation.section.embedded"
            ]
        },
        {
            "settings": {
                "foreground": "#000000"
            },
            "name": "Reset JavaScript string interpolation expression",
            "scope": [
                "meta.template.expression"
            ]
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "scope": [
                "support.constant.property-value",
                "support.constant.font-name",
                "support.constant.media-type",
                "support.constant.media",
                "constant.other.color.rgb-value",
                "constant.other.rgb-value",
                "support.constant.color"
            ]
        },
        {
            "settings": {
                "foreground": "#e50000"
            },
            "scope": [
                "support.type.vendored.property-name",
                "support.type.property-name",
                "source.css variable",
                "source.coffee.embedded"
            ]
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "scope": [
                "support.type.property-name.json"
            ]
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": "keyword"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": "keyword.control"
        },
        {
            "settings": {
                "foreground": "#000000"
            },
            "scope": "keyword.operator"
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": [
                "keyword.operator.new",
                "keyword.operator.expression",
                "keyword.operator.cast",
                "keyword.operator.sizeof",
                "keyword.operator.alignof",
                "keyword.operator.typeid",
                "keyword.operator.alignas",
                "keyword.operator.instanceof",
                "keyword.operator.logical.python",
                "keyword.operator.wordlike"
            ]
        },
        {
            "settings": {
                "foreground": "#098658"
            },
            "scope": "keyword.other.unit"
        },
        {
            "settings": {
                "foreground": "#800000"
            },
            "scope": [
                "punctuation.section.embedded.begin.php",
                "punctuation.section.embedded.end.php"
            ]
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "scope": "support.function.git-rebase"
        },
        {
            "settings": {
                "foreground": "#098658"
            },
            "scope": "constant.sha.git-rebase"
        },
        {
            "settings": {
                "foreground": "#000000"
            },
            "name": "coloring of the Java import and package identifiers",
            "scope": [
                "storage.modifier.import.java",
                "variable.language.wildcard.java",
                "storage.modifier.package.java"
            ]
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "name": "this.self",
            "scope": "variable.language"
        },
        {
            "settings": {
                "foreground": "#795E26"
            },
            "name": "Function declarations",
            "scope": [
                "entity.name.function",
                "support.function",
                "support.constant.handlebars",
                "source.powershell variable.other.member",
                "entity.name.operator.custom-literal"
            ]
        },
        {
            "settings": {
                "foreground": "#267f99"
            },
            "name": "Types declaration and references",
            "scope": [
                "support.class",
                "support.type",
                "entity.name.type",
                "entity.name.namespace",
                "entity.other.attribute",
                "entity.name.scope-resolution",
                "entity.name.class",
                "storage.type.numeric.go",
                "storage.type.byte.go",
                "storage.type.boolean.go",
                "storage.type.string.go",
                "storage.type.uintptr.go",
                "storage.type.error.go",
                "storage.type.rune.go",
                "storage.type.cs",
                "storage.type.generic.cs",
                "storage.type.modifier.cs",
                "storage.type.variable.cs",
                "storage.type.annotation.java",
                "storage.type.generic.java",
                "storage.type.java",
                "storage.type.object.array.java",
                "storage.type.primitive.array.java",
                "storage.type.primitive.java",
                "storage.type.token.java",
                "storage.type.groovy",
                "storage.type.annotation.groovy",
                "storage.type.parameters.groovy",
                "storage.type.generic.groovy",
                "storage.type.object.array.groovy",
                "storage.type.primitive.array.groovy",
                "storage.type.primitive.groovy"
            ]
        },
        {
            "settings": {
                "foreground": "#267f99"
            },
            "name": "Types declaration and references, TS grammar specific",
            "scope": [
                "meta.type.cast.expr",
                "meta.type.new.expr",
                "support.constant.math",
                "support.constant.dom",
                "support.constant.json",
                "entity.other.inherited-class",
                "punctuation.separator.namespace.ruby"
            ]
        },
        {
            "settings": {
                "foreground": "#AF00DB"
            },
            "name": "Control flow / Special keywords",
            "scope": [
                "keyword.control",
                "source.cpp keyword.operator.new",
                "source.cpp keyword.operator.delete",
                "keyword.other.using",
                "keyword.other.directive.using",
                "keyword.other.operator",
                "entity.name.operator"
            ]
        },
        {
            "settings": {
                "foreground": "#001080"
            },
            "name": "Variable and parameter name",
            "scope": [
                "variable",
                "meta.definition.variable.name",
                "support.variable",
                "entity.name.variable",
                "constant.other.placeholder"
            ]
        },
        {
            "settings": {
                "foreground": "#0070C1"
            },
            "name": "Constants and enums",
            "scope": [
                "variable.other.constant",
                "variable.other.enummember"
            ]
        },
        {
            "settings": {
                "foreground": "#001080"
            },
            "name": "Object keys, TS grammar specific",
            "scope": [
                "meta.object-literal.key"
            ]
        },
        {
            "settings": {
                "foreground": "#0451a5"
            },
            "name": "CSS property value",
            "scope": [
                "support.constant.property-value",
                "support.constant.font-name",
                "support.constant.media-type",
                "support.constant.media",
                "constant.other.color.rgb-value",
                "constant.other.rgb-value",
                "support.constant.color"
            ]
        },
        {
            "settings": {
                "foreground": "#d16969"
            },
            "name": "Regular expression groups",
            "scope": [
                "punctuation.definition.group.regexp",
                "punctuation.definition.group.assertion.regexp",
                "punctuation.definition.character-class.regexp",
                "punctuation.character.set.begin.regexp",
                "punctuation.character.set.end.regexp",
                "keyword.operator.negation.regexp",
                "support.other.parenthesis.regexp"
            ]
        },
        {
            "settings": {
                "foreground": "#811f3f"
            },
            "scope": [
                "constant.character.character-class.regexp",
                "constant.other.character-class.set.regexp",
                "constant.other.character-class.regexp",
                "constant.character.set.regexp"
            ]
        },
        {
            "settings": {
                "foreground": "#000000"
            },
            "scope": "keyword.operator.quantifier.regexp"
        },
        {
            "settings": {
                "foreground": "#EE0000"
            },
            "scope": [
                "keyword.operator.or.regexp",
                "keyword.control.anchor.regexp"
            ]
        },
        {
            "settings": {
                "foreground": "#0000ff"
            },
            "scope": [
                "constant.character",
                "constant.other.option"
            ]
        },
        {
            "settings": {
                "foreground": "#EE0000"
            },
            "scope": "constant.character.escape"
        },
        {
            "settings": {
                "foreground": "#000000"
            },
            "scope": "entity.name.label"
        }
    ]
};
