import { mkdirSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";

import { screenshotsDir } from "../helpers/renderScreenshot.ts";

import { type CapturedShot, loadScenarios, runScenario } from "./framework.ts";

// `npm run screenshots` — regenerate every scenario's PNGs into the git-ignored
// screenshots/ dir plus an INDEX.md gallery. Attach the produced PNGs to the PR.

async function main(): Promise<void> {
    const scenarios = await loadScenarios();
    if (scenarios.length === 0) {
        process.stdout.write("No scenarios found in e2e/scenarios/.\n");
        return;
    }

    const captured: CapturedShot[] = [];
    for (const spec of scenarios) {
        process.stdout.write(`▶ ${spec.name}\n`);
        const shots = await runScenario(spec);
        captured.push(...shots);
        for (const shot of shots) {
            process.stdout.write(`  ✓ ${relative(process.cwd(), shot.path)}\n`);
        }
    }

    writeIndex(captured);
    process.stdout.write(`\nWrote ${String(captured.length)} screenshot(s) to ${screenshotsDir}\n`);
}

function writeIndex(shots: CapturedShot[]): void {
    mkdirSync(screenshotsDir, { recursive: true });
    const lines: string[] = ["# Screenshots", "", "_Auto-generated by `npm run screenshots`._", ""];
    let current = "";
    for (const shot of shots) {
        if (shot.scenario !== current) {
            lines.push(`## ${shot.title}`, "");
            current = shot.scenario;
        }
        const file = relative(screenshotsDir, shot.path);
        lines.push(`**${shot.shot}**`, "", `![${shot.title} — ${shot.shot}](${file})`, "");
    }
    writeFileSync(resolve(screenshotsDir, "INDEX.md"), lines.join("\n"));
}

await main();
process.exit(0);
